pipeline:
  name: test-3
  identifier: test3
  projectIdentifier: mysteriousbeggarhws130
  orgIdentifier: event_hws130
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Gaurav_Private
        repoName: Java-example
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: xxxlarge
              imageSpec:
                imageName: ubuntu-latest
          execution:
            steps:
              - step:
                  type: Run
                  name: Run CI with Maven
                  identifier: Run_CI_with_Maven
                  spec:
                    connectorRef: dockerhub_devsecops
                    image: maven:3.9.16-eclipse-temurin-25
                    shell: Sh
                    command: |-
                      java -version
                      ./mvnw --batch-mode --file pom.xml verify package
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_2
                  identifier: BuildAndPushDockerRegistry_2
                  spec:
                    connectorRef: dockerhub_devsecops
                    repo: nikpap/harness-workshop
                    tags:
                      - <+codebase.shortCommitSha>
                      - build-<+pipeline.sequenceId>
                    caching: true
                    dockerfile: Dockerfile
                contextType: Pipeline
              - step:
                  name: Fortify
                  identifier: Fortify
                  template:
                    templateRef: fortify
                    versionLabel: v0.1
              - step:
                  name: OWASP
                  identifier: OWASP
                  template:
                    templateRef: owasp
                    versionLabel: v0.1
