pipeline:
  name: test-3
  identifier: test3
  projectIdentifier: Test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Gaurav_Private_GitHub
        repoName: Java-example
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec:
              size: xxxlarge
          execution:
            steps:
              - step:
                  type: Run
                  name: Launch GitHub Workflow
                  identifier: Launch_GitHub_Workflow
                  spec:
                    shell: Sh
                    command: |-
                      curl -L \
                        -X POST \
                        -H "Accept: application/vnd.github+json" \
                        -H "Authorization: Bearer $GITHUB_PAT" \
                        -H "X-GitHub-Api-Version: 2026-03-10" \
                        https://api.github.com/repos/gauravphadke/Java-example/actions/workflows/harness-triggered.yml/dispatches \
                        -d '{"ref":"main"}'
                    envVariables:
                      GITHUB_PAT: <+secrets.getValue("GitHub_PAT")>
        sendGitStatus:
          enabled: false
          name: ""
