pipeline:
  name: test-3
  identifier: test3
  projectIdentifier: Test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Gaurav_Private_GitHub
        repoName: Java-example
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: xxxlarge
              imageSpec:
                imageName: ubuntu-latest
          execution:
            steps:
              - stepGroup:
                  name: Build And Dockerize
                  identifier: Build_And_Dockerize
                  steps:
                    - parallel:
                        - step:
                            type: Run
                            name: Run CI with Maven
                            identifier: Run_CI_with_Maven
                            spec:
                              connectorRef: dockerhub_devsecops
                              image: maven:3.9.16-eclipse-temurin-25
                              shell: Sh
                              command: |-
                                java -version
                                ./mvnw --batch-mode --file pom.xml verify package
                        - step:
                            type: BuildAndPushDockerRegistry
                            name: BuildAndPushDockerRegistry_2
                            identifier: BuildAndPushDockerRegistry_2
                            spec:
                              connectorRef: dockerhub_devsecops
                              repo: gauravphadkep/harness-workshop
                              tags:
                                - <+codebase.shortCommitSha>
                                - build-<+pipeline.sequenceId>
                              caching: true
                              dockerfile: Dockerfile
                          contextType: Pipeline
